import 'package:flutter/material.dart';
import 'nft_model.dart';

List<NFTDataModel> nftList = [
  NFTDataModel(
    name: "CryptoPunk #001",
    description: "A rare CryptoPunk collectible.",
    image: "https://via.placeholder.com/150",
    owner: "Alice",
    price: "3.5 ETH",
    number: "001",
    color: Colors.blue[100], // Background color
    days: "2",
    hours: "5",
    minutes: "30",
  ),
  NFTDataModel(
    name: "Bored Ape #777",
    description: "Exclusive Bored Ape Yacht Club member.",
    image: "https://via.placeholder.com/150",
    owner: "Bob",
    price: "12.0 ETH",
    number: "777",
    color: Colors.yellow[100],
    days: "4",
    hours: "12",
    minutes: "10",
  ),
  NFTDataModel(
    name: "Space Doodle #420",
    description: "A unique space-themed NFT art.",
    image: "https://via.placeholder.com/150",
    owner: "Charlie",
    price: "7.8 ETH",
    number: "420",
    color: Colors.purple[100],
    days: "1",
    hours: "8",
    minutes: "45",
  ),
  NFTDataModel(
    name: "Mutant Ape #999",
    description: "Mutant version of the famous Bored Ape.",
    image: "https://via.placeholder.com/150",
    owner: "David",
    price: "9.3 ETH",
    number: "999",
    color: Colors.red[100],
    days: "3",
    hours: "6",
    minutes: "15",
  ),
  NFTDataModel(
    name: "MechaVerse #102",
    description: "A futuristic robot NFT collectible.",
    image: "https://via.placeholder.com/150",
    owner: "Emma",
    price: "5.2 ETH",
    number: "102",
    color: Colors.green[100],
    days: "5",
    hours: "14",
    minutes: "50",
  ),
];
